### ISSUE TITLE
There is no URL for me to play doggle

### ISSUE THREAD

**Issue by alex-page** [charmasaur/doggle#1]
Rude.

**Comment by charmasaur** [comment]
Damn, sorry. playdoggle.herokuapp.com. Will put it on the readme next time I'm on a computer.

**Comment by charmasaur** [comment]
It's pretty basic atm though, don't judge too harshly. PRs to improve things most welcome.

**Comment by alex-page** [comment]
Amazing ty @charmasaur 🎉
